First pass at supporting integration into multiple machines. 1) Added logic to handle per-system fzf version diffs AMD vs personal machine. 2) Fixed crash of log.do by simplifying code-- no indirection to infra script, code for logging is stored in the log do-file.

diff --git a/make_taskdir b/make_taskdir
--- a/make_taskdir
+++ b/make_taskdir
@@ -5,10 +5,19 @@ source "$HERE"/bash_utils
 TODOROOT=$(dirname $(dirname $(realpath $(which "$0"))))
 context_header=${1:-''}
 
-#For consistent UX experience thru-out task-sys, even tho bash read would be equivalent here
-run 'echo "" | fzf --prompt="WRITE_GOAL -- 1-3 concrete sentences >" --header="$context_header" --print-query --gap=1'
+#Accounts for argument --gap=1 not supported by fzf version 0.54.2 used on AMD machine
+if cat /etc/os-release 2> /dev/null | grep -q 'NAME="Red Hat Enterprise Linux"'; then #AMD machine
+    fzf_gap_arg=''
+else #personal machine
+    fzf_gap_arg='--gap=1'
+fi
+
+#Using fzf for consistent UX experience thru-out task-sys, even tho bash read would be equivalent here
+run 'echo "" | fzf --prompt="WRITE_GOAL -- 1-3 concrete sentences >" --header="$context_header" --print-query $fzf_gap_arg'
 exit_code=$?
+
 if [ "$exit_code" -gt "1" ] ; then
+    echo "ERROR: fzf had unexpected exit code: $exit_code" >&2
 	exit "$exit_code"
 fi
 goal=$(
@@ -35,6 +44,7 @@ estimated_time_suggestions=$(
 	echo "1.50       1h 30m"
 	echo "2          2h"
 	echo "3          3h"
+    #anything past 3h is sus, suggests it should prob be broken into separate tasks, but i am leaving this for now
 	echo "4          4h"
 	echo "5          5h"
 	echo "6          6h"
@@ -42,33 +52,8 @@ estimated_time_suggestions=$(
 	echo "8          8h"
 	echo "9          9h"
 	echo "10         10h"
-	#these have never been used, and having goals this large is probably pathological, as they should be broken up into a series of smaller goals instead
-	#echo "24         1d"
-	#echo "36         1d 12h"
-	#echo "48         2d"
-	#echo "72         3d"
-	#echo "96         4d"
-	#echo "120        5d"
-	#echo "144        6d"
-	#echo "168        1w"
-	#echo "264        1w 4d"
-	#echo "336        2w"
-	#echo "504        3w"
-	#echo "672        1mo"
-	#echo "1008       1mo 2w"
-	#echo "1344       2mo"
-	#echo "2016       3mo"
-	#echo "2688       4mo"
-	#echo "3360       5mo"
-	#echo "4032       6mo"
-	#echo "4704       7mo"
-	#echo "5376       8mo"
-	#echo "6048       9mo"
-	#echo "6720       10mo"
-	#echo "7392       11mo"
-	#echo "8064       1y"
 )
-crash_if_nonzero_exit 'echo "$estimated_time_suggestions" | fzf --prompt="EXPECTED_WORK_HOURS -- $goal >" --header="HOURS	   AKA" --gap=1'
+crash_if_nonzero_exit 'echo "$estimated_time_suggestions" | fzf --prompt="EXPECTED_WORK_HOURS -- $goal >" --header="HOURS	   AKA" $fzf_gap_arg'
 planning_fallacy_penalty=1.75
 estimated_time=$(dc --expression="2 k $(echo "$STDOUT" | awk '{print $1}') $planning_fallacy_penalty * p") #planning fallacy penalty: assume things will take x2 longer than you think
 
@@ -77,11 +62,12 @@ mkdir $taskdir
 touch $taskdir/::$goal.hmm
 touch $taskdir/:by_?
 touch $taskdir/:time=${estimated_time}h
-cp $TODOROOT/.infra/log.do $taskdir/log.do
+cat "$HERE"/log.do | sed "s:bash_utils:$HERE/bash_utils:g" > $taskdir/log.do
+chmod +x $taskdir/log.do
 
 do_it_now_cutoff=0.25	#15 minutes
 if (( $(echo "$estimated_time <= $do_it_now_cutoff" | bc -l) )); then #if the goal can be done quickly, do it now
-	mark $taskdir 0_now
+	"$HERE"/mark $taskdir 0_now
 	taskdir=$(find "$TODOROOT/0_now" -type f -name "$goal.hmm" -exec dirname {} \; | head -n 1)
 fi
 
